@extends('layouts.admin')
@section('title','Delivery Team')
@section('admin-content')
<div class="admin-heading"><div><span class="kicker dark">Own-fleet operations</span><h1>Delivery team</h1><p>Create verified driver accounts and assign paid shipments.</p></div></div>
<div class="driver-admin-grid">
<section class="admin-panel"><h2>Create driver</h2><form class="driver-create-form" method="POST" action="{{ route('admin.drivers.store') }}">@csrf<label>Name<input name="name" required></label><label>Email<input type="email" name="email" required></label><label>Phone<input type="tel" name="phone" required></label><label>Temporary password<input type="password" name="password" minlength="10" required></label><button class="button" type="submit">Create driver account</button></form><p class="admin-panel-note">Share temporary credentials through a secure channel. Production should add driver MFA and mandatory password change.</p></section>
<section class="admin-panel"><h2>Drivers</h2><div class="driver-list">@forelse($drivers as $driver)<article><span class="driver-avatar">{{ strtoupper(substr($driver->name,0,1)) }}</span><div><b>{{ $driver->name }}</b><small>{{ $driver->email }} · {{ $driver->phone }}</small><small>{{ $driver->delivery_assignments_count }} assignments</small></div><form method="POST" action="{{ route('admin.drivers.toggle',$driver) }}">@csrf @method('PATCH')<button class="{{ $driver->is_active?'danger-link':'success-link' }}" type="submit">{{ $driver->is_active?'Disable':'Enable' }}</button></form></article>@empty<div class="admin-empty"><strong>No drivers yet</strong><span>Create the first verified delivery account.</span></div>@endforelse</div></section>
</div>
<section class="admin-panel"><div class="section-heading"><div><span class="eyebrow">Paid shipments</span><h2>Delivery assignments</h2></div></div><div class="admin-table assignment-table"><div class="table-row table-head"><span>Tracking / order</span><span>Customer</span><span>Status</span><span>Assigned driver</span><span>Assign</span></div>@forelse($shipments as $shipment)<div class="table-row"><span><b>{{ $shipment->tracking_number }}</b><small>{{ $shipment->order->reference }}</small></span><span><b>{{ $shipment->order->user->name }}</b><small>{{ data_get($shipment->order->shipping_address,'city') }}, {{ data_get($shipment->order->shipping_address,'state') }}</small></span><span class="status status-{{ $shipment->status }}">{{ str_replace('_',' ',$shipment->status) }}</span><span><b>{{ $shipment->assignment?->driver?->name ?? 'Unassigned' }}</b><small>{{ $shipment->assignment?->status }}</small></span><form class="inline-update" method="POST" action="{{ route('admin.shipments.assign',$shipment) }}">@csrf<select name="driver_id" required><option value="">Select driver</option>@foreach($drivers->where('is_active',true) as $driver)<option value="{{ $driver->id }}" @selected($shipment->assignment?->driver_id===$driver->id)>{{ $driver->name }}</option>@endforeach</select><button type="submit">Assign</button></form></div>@empty<div class="admin-empty"><strong>No paid shipments</strong><span>Tracking records appear after verified payment.</span></div>@endforelse</div></section>
@endsection
