<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Purchase confirmed</title></head>
<body style="margin:0;background:#f3f1ea;color:#17231f;font-family:Arial,sans-serif;">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f3f1ea;padding:24px 10px;"><tr><td align="center">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#ffffff;border-collapse:collapse;">
<tr><td style="background:#102f28;padding:24px 30px;color:#ffffff;"><table role="presentation" width="100%"><tr><td><div style="font-size:20px;font-weight:700;letter-spacing:3px;">N &amp; H</div><div style="font-size:9px;color:#e4c77d;letter-spacing:4px;">TRUST</div></td><td align="right" style="font-size:12px;color:#c8d8d1;">CERTIFIED GOLD COMMERCE</td></tr></table></td></tr>
<tr><td style="padding:30px;"><div style="color:#b8862f;font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;">Payment confirmed</div><h1 style="font-family:Georgia,serif;font-size:30px;margin:8px 0 10px;color:#173b32;">Thank you for your purchase.</h1><p style="margin:0 0 18px;color:#596761;line-height:1.6;">Hello {{ $order->user->name }}, your payment has been verified and your certified gold order is now in secure fulfilment.</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f7f5ef;border:1px solid #e2dfd5;margin-bottom:22px;"><tr><td style="padding:14px;"><small style="color:#77827d;text-transform:uppercase;">Order reference</small><br><strong>{{ $order->reference }}</strong></td><td style="padding:14px;"><small style="color:#77827d;text-transform:uppercase;">Amount paid</small><br><strong>₹{{ number_format($order->total,2) }}</strong></td>@if($order->shipment)<td style="padding:14px;"><small style="color:#77827d;text-transform:uppercase;">Tracking ID</small><br><strong>{{ $order->shipment->tracking_number }}</strong></td>@endif</tr></table>
<h2 style="font-family:Georgia,serif;font-size:20px;color:#173b32;margin:0 0 10px;">Purchase details</h2>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
@foreach($order->items as $item)
<tr style="border-bottom:1px solid #e6e6e0;"><td width="76" style="padding:12px 8px 12px 0;">@php($image=$productImages[$item->id]??null)@if(data_get($image,'path'))<img src="{{ $message->embed(data_get($image,'path')) }}" width="64" height="64" alt="" style="display:block;object-fit:cover;border:1px solid #e1e1dc;">@elseif(data_get($image,'url'))<img src="{{ data_get($image,'url') }}" width="64" height="64" alt="" style="display:block;object-fit:cover;border:1px solid #e1e1dc;">@endif</td><td style="padding:12px 8px;"><strong style="font-size:14px;">{{ data_get($item->product_snapshot,'name') }}</strong><br><small style="color:#75817b;">{{ data_get($item->product_snapshot,'purity') }} · {{ data_get($item->product_snapshot,'weight_grams') }}g · Qty {{ $item->quantity }}</small><br><small style="color:#75817b;">{{ data_get($item->product_snapshot,'certification') }}</small></td><td align="right" style="padding:12px 0 12px 8px;font-weight:700;white-space:nowrap;">₹{{ number_format($item->line_total,2) }}</td></tr>
@endforeach
</table>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:18px;"><tr><td width="48%"></td><td><table role="presentation" width="100%"><tr><td style="padding:4px;color:#69756f;">Product value</td><td align="right">₹{{ number_format($order->subtotal,2) }}</td></tr><tr><td style="padding:4px;color:#69756f;">GST</td><td align="right">₹{{ number_format($order->tax,2) }}</td></tr><tr><td style="padding:4px;color:#69756f;">Delivery</td><td align="right">₹{{ number_format($order->delivery_charge,2) }}</td></tr><tr><td style="padding:4px;color:#69756f;">Discount</td><td align="right">− ₹{{ number_format($order->discount,2) }}</td></tr><tr><td style="padding:10px 4px;border-top:2px solid #173b32;font-weight:700;">Total</td><td align="right" style="padding:10px 0;border-top:2px solid #173b32;font-weight:700;">₹{{ number_format($order->total,2) }}</td></tr></table></td></tr></table>
<div style="text-align:center;margin-top:26px;">@if($order->shipment)<a href="{{ route('orders.tracking',$order) }}" style="display:inline-block;background:#173b32;color:#ffffff;text-decoration:none;padding:13px 22px;font-weight:700;font-size:13px;">Track delivery</a>@endif <a href="{{ route('orders.show',$order) }}" style="display:inline-block;border:1px solid #173b32;color:#173b32;text-decoration:none;padding:12px 22px;font-weight:700;font-size:13px;">View order</a></div>
<p style="font-size:11px;color:#7b8580;line-height:1.5;margin:24px 0 0;">Your PDF invoice is attached. Never share an OTP, card PIN or payment credential with anyone claiming to be support.</p>
</td></tr>
<tr><td style="background:#f7f5ef;border-top:1px solid #e0ddd4;padding:18px 30px;color:#6f7a75;font-size:11px;line-height:1.5;">N &amp; H Trust · {{ config('commerce.support_email') }} · {{ config('commerce.support_phone') }}</td></tr>
</table></td></tr></table></body></html>
