@extends('layouts.driver')
@section('title',$assignment->shipment->tracking_number)
@section('content')
<a class="driver-back" href="{{ route('driver.dashboard') }}">← My deliveries</a>
<section class="driver-delivery-hero"><div><span>Tracking ID</span><h1>{{ $assignment->shipment->tracking_number }}</h1><p>Order {{ $assignment->shipment->order->reference }}</p></div><span class="status status-{{ $assignment->status }}" id="assignment-status">{{ $assignment->status }}</span></section>
<div class="driver-detail-grid"><section class="driver-panel"><h2>Delivery address</h2><p><b>{{ data_get($assignment->shipment->order->shipping_address,'full_name') }}</b><br>{{ data_get($assignment->shipment->order->shipping_address,'address_line_1') }}<br>{{ data_get($assignment->shipment->order->shipping_address,'address_line_2') }}<br>{{ data_get($assignment->shipment->order->shipping_address,'city') }}, {{ data_get($assignment->shipment->order->shipping_address,'state') }} {{ data_get($assignment->shipment->order->shipping_address,'postal_code') }}</p><p><a href="tel:{{ data_get($assignment->shipment->order->shipping_address,'phone') }}">Call customer: {{ data_get($assignment->shipment->order->shipping_address,'phone') }}</a></p></section><section class="driver-panel"><h2>Location sharing</h2><p id="location-message">Location is off. It is sent only while this page is open and delivery is active.</p><button class="button full" type="button" id="location-toggle" @disabled(!in_array($assignment->status,['accepted','active'],true))>Start location sharing</button><div class="driver-location-stats"><span>Accuracy <b id="gps-accuracy">—</b></span><span>Last sent <b id="gps-sent">—</b></span></div></section></div>
<section class="driver-panel driver-actions"><h2>Delivery actions</h2>@if($assignment->status==='assigned')<form method="POST" action="{{ route('driver.deliveries.accept',$assignment) }}">@csrf<button class="button" type="submit">Accept delivery</button></form>@elseif($assignment->status==='accepted')<form method="POST" action="{{ route('driver.deliveries.start',$assignment) }}">@csrf<button class="button" type="submit">Start delivery</button></form>@elseif($assignment->status==='active')<form method="POST" action="{{ route('driver.deliveries.complete',$assignment) }}" onsubmit="return confirm('Confirm that the customer received the package?')">@csrf<button class="button" type="submit">Mark delivered</button></form>@else<p>No further action is available for this assignment.</p>@endif</section>
<section class="driver-panel"><h2>Shipment timeline</h2><ol class="driver-timeline">@foreach($assignment->shipment->events as $event)<li><span></span><div><b>{{ $event->title }}</b><p>{{ $event->description }}</p><small>{{ $event->occurred_at->format('d M Y, h:i A') }}</small></div></li>@endforeach</ol></section>
<div class="driver-security"><b>Security:</b> Verify the customer and physical handover before marking delivered. Never request a payment OTP or card PIN.</div>
@endsection
@push('scripts')
<script>
window.addEventListener('load',()=>{const button=document.getElementById('location-toggle');if(!button)return;const endpoint=@json(route('driver.deliveries.location',$assignment));const csrf=document.querySelector('meta[name="csrf-token"]').content;let watchId=null;let lastSent=0;const send=async position=>{if(Date.now()-lastSent<15000)return;lastSent=Date.now();const payload={latitude:position.coords.latitude,longitude:position.coords.longitude,accuracy:position.coords.accuracy,heading:position.coords.heading,speed:position.coords.speed};const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':csrf,'Accept':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('Location update failed');document.getElementById('gps-accuracy').textContent=Math.round(position.coords.accuracy)+' m';document.getElementById('gps-sent').textContent=new Date().toLocaleTimeString('en-IN');document.getElementById('location-message').textContent='Approximate location is being shared securely.';};button.addEventListener('click',()=>{if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;button.textContent='Start location sharing';document.getElementById('location-message').textContent='Location sharing stopped.';return;}if(!navigator.geolocation){document.getElementById('location-message').textContent='This browser does not support location.';return;}watchId=navigator.geolocation.watchPosition(position=>send(position).catch(error=>{document.getElementById('location-message').textContent=error.message;}),error=>{document.getElementById('location-message').textContent='Location permission/error: '+error.message;},{enableHighAccuracy:true,maximumAge:10000,timeout:15000});button.textContent='Stop location sharing';});});
</script>
@endpush
